name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write 

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate GitHub contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: TheHMBB
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push to Snake branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: Snake
          build_dir: dist
          color_dots: '#d1d5da,#8abeb7,#81a2be,#b294bb,#cc6666'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
